language: swift
osx_image: xcode11

script:
  set -o pipefail &&
  travis_retry
  xcodebuild build test
  -workspace CotEditor.xcworkspace
  -scheme CotEditor
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
  | xcpretty
